//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Hcl.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="HclParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IHclListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocument([NotNull] HclParser.DocumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.document"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocument([NotNull] HclParser.DocumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] HclParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] HclParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.blockLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockLabel([NotNull] HclParser.BlockLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.blockLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockLabel([NotNull] HclParser.BlockLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBody([NotNull] HclParser.BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBody([NotNull] HclParser.BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttribute([NotNull] HclParser.AttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.attribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttribute([NotNull] HclParser.AttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.nestedBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNestedBlock([NotNull] HclParser.NestedBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.nestedBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNestedBlock([NotNull] HclParser.NestedBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.indexedAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexedAttribute([NotNull] HclParser.IndexedAttributeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.indexedAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexedAttribute([NotNull] HclParser.IndexedAttributeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterList([NotNull] HclParser.ListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitList([NotNull] HclParser.ListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMap([NotNull] HclParser.MapContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMap([NotNull] HclParser.MapContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.mapEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapEntry([NotNull] HclParser.MapEntryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.mapEntry"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapEntry([NotNull] HclParser.MapEntryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.mapKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMapKey([NotNull] HclParser.MapKeyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.mapKey"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMapKey([NotNull] HclParser.MapKeyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.multilineString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultilineString([NotNull] HclParser.MultilineStringContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.multilineString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultilineString([NotNull] HclParser.MultilineStringContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] HclParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] HclParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.interpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterpolation([NotNull] HclParser.InterpolationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.interpolation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterpolation([NotNull] HclParser.InterpolationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReference([NotNull] HclParser.ReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReference([NotNull] HclParser.ReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.indexedReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIndexedReference([NotNull] HclParser.IndexedReferenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.indexedReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIndexedReference([NotNull] HclParser.IndexedReferenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] HclParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] HclParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="HclParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] HclParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="HclParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] HclParser.ExpressionContext context);
}
